Feature/cris 10455 package temperature sensor ros
KABAM-Robotics/temper-ros pull request #2
Opened 2023-06-13 03:42 UTC by camilleconcepcion3012

2023-06-13 08:14 UTC, arwinder-jaspal requested changes

2023-06-13 08:14 UTC, arwinder-jaspal commented on Dockerfile
do we need this Dockerfile in this repo?

2023-06-13 08:14 UTC, arwinder-jaspal commented on package.xml
Let's make it a practice to remove unused lines. It doesn't affect performance, but since this is a public repository, others can see this.

2023-06-14 01:08 UTC, camilleconcepcion3012 commented on Dockerfile
You previously mentioned that I should add the dockerfile to this repo. I can remove it if you like

2023-06-14 01:09 UTC, camilleconcepcion3012 commented on package.xml
Noted.

2023-06-14 02:47 UTC, arwinder-jaspal commented on Dockerfile
let's remove it.

2023-06-22 09:52 UTC, arwinder-jaspal approved these changes

2023-06-22 09:52 UTC, merged